<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'fpdi' => array($vendorDir . '/itbz/fpdi/src'),
    'fpdf' => array($vendorDir . '/itbz/fpdf/src'),
    'WebLoader' => array($vendorDir . '/janmarek/webloader'),
    'ProxyManager\\' => array($vendorDir . '/ocramius/proxy-manager/src'),
    'PhpOption\\' => array($vendorDir . '/phpoption/phpoption/src'),
    'PhpCollection' => array($vendorDir . '/phpcollection/phpcollection/src'),
    'Nella\\Doctrine' => array($vendorDir . '/nella/doctrine'),
    'Nella\\Console' => array($vendorDir . '/nella/console'),
    'Metadata\\' => array($vendorDir . '/jms/metadata/src'),
    'JMS\\Serializer' => array($vendorDir . '/jms/serializer/src'),
    'JMS\\' => array($vendorDir . '/jms/parser-lib/src'),
    'Doctrine\\ORM' => array($vendorDir . '/doctrine/orm/lib'),
    'Doctrine\\DBAL' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Doctrine\\Common\\DataFixtures' => array($vendorDir . '/doctrine/data-fixtures/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib'),
    'Doctrine\\Common\\' => array($vendorDir . '/doctrine/common/lib'),
);
